name = "KronLinInv"
uuid = "cc83e5c8-98fc-11e9-313e-e750fdcd15c8"
authors = ["Andrea Zunino <inverseproblem@users.noreply.github.com>"]
version = "0.2.0"

[deps]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
